version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.3.5-node
    working_directory: ~/granite
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "22.20.0"
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: yarn install --cache-folder vendor/node_modules
      - run: bundle exec rubocop
      - run: |
          npx eslint "./app/javascript/src/**/*.{js,jsx,json}"
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:schema:load --trace
      - run: chmod a+x ./bin/webpacker && ./bin/webpacker
      - run: bundle exec rails webpacker:compile
workflows:
  version: 2
  commit:
    jobs:
      - build
